layout_spectrum: 0.5703480137588621
typography_spectrum: 0.09936183882047339
color:
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  brandStrength: 0.19385561064208426
  lightness: 0.12883612160266625
  saturation: 0.5031874807629881
  rhythmicContrast: 0.8030681849457324
coverPrefs:
  filter: false
content_rating:
  adult: false
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-84067528-1
  facebook: null
  twitter: null
author:
  name: Silas Drewchin
  email: ''
logo: null
name: Silas Drewchin
url: 'https://thegrid.ai/sidrewchin'
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: SPACE//OBJECT//FREQUENCY
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: video
    html: >-
      <iframe
      src="https://cdn.embedly.com/widgets/media.html?src=https%3A%2F%2Fplayer.vimeo.com%2Fvideo%2F303286558%3Fapp_id%3D122963&dntp=1&url=https%3A%2F%2Fvimeo.com%2F303286558&image=https%3A%2F%2Fi.vimeocdn.com%2Fvideo%2F747609418_1280.jpg&key=a715cf41cc93453ca338d350cd26f87b&type=text%2Fhtml&schema=vimeo"
      width="1000" height="563" scrolling="no" frameborder="0"
      allowfullscreen="true"></iframe>
    src: !<tag:yaml.org,2002:js/undefined> ''
    metadata:
      author:
        - name: 'another:'
          url: 'https://vimeo.com/user92210789'
          avatar: {}
      related: []
      publisher:
        url: 'https://vimeo.com/'
        name: Vimeo
        favicon: 'https://f.vimeocdn.com/images_v6/favicon.ico?DEV'
        domain: vimeo.com
      keywords: []
      description: >-
        another : approach to expand the field of view, or rather to create a
        vision, which had never been perceived. another : THE ORB a film by
        laurian ghinitoiu & arata mori music by yu miyashita
        https://www.facebook.com/anothertwo2 http://www.laurianghinitoiu.com |
        http://www.aratamori.com | https://underarrow.com
      '@type': VideoObject
      app_links:
        - url: 'vimeo://app.vimeo.com/videos/303286558'
          type: ios
          namespace: ai
          app_name: Vimeo
          app_store_id: '425194759'
        - should_fallback: 'true'
          app_name: Vimeo
          package: com.vimeo.android.videoapp
          url: 'vimeo://app.vimeo.com/videos/303286558'
          namespace: ai
          type: web
        - url: 'vimeo://app.vimeo.com/videos/303286558'
          namespace: twitter
          type: ipad
          name: Vimeo
          id: '425194759'
        - url: 'vimeo://app.vimeo.com/videos/303286558'
          namespace: twitter
          type: iphone
          name: Vimeo
          id: '425194759'
        - url: 'vimeo://app.vimeo.com/videos/303286558'
          namespace: twitter
          type: googleplay
          name: Vimeo
          id: com.vimeo.android.videoapp
      '@context': 'http://schema.org'
      isBasedOnUrl: 'https://vimeo.com/303286558'
      title: 'another : THE ORB'
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Opening Doors, Creating Paths'
purpose:
  - type: external
    url: 'http://plantgroup.co'
    label: Plant Group
  - type: external
    url: 'http://konsol.xyz'
    label: 'PAD '
github: true
