layout_spectrum: 0.5703480137588621
typography_spectrum: 0.09936183882047339
color:
  brandColors:
    - '#004358'
    - '#1F8A70'
    - '#BEDB39'
    - '#FFE11A'
    - '#FD7400'
  brandStrength: 0.19385561064208426
  lightness: 0.12883612160266625
  saturation: 0.5031874807629881
  rhythmicContrast: 0.8030681849457324
coverPrefs:
  filter: false
content_rating:
  adult: false
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: UA-84067528-1
  facebook: null
  twitter: null
author:
  name: Silas Drewchin
  email: ''
logo: null
name: Silas Drewchin
url: 'https://thegrid.ai/sidrewchin'
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: SPACE//OBJECT//FREQUENCY
content: []
description: 'Opening Doors, Creating Paths'
purpose:
  - type: external
    url: 'http://plantgroup.co'
    label: Plant Group
  - type: external
    url: 'http://konsol.xyz'
    label: 'PAD '
github: true
