name: Silas Drew-Ch(Innes)
favicon: null
layout_spectrum: 1
typography_spectrum: 0.4669428579509258
coverPrefs:
  filter: false
content_rating:
  adult: false
title: ART x PHILOSOPHY = ARCHITECTURE
description: Professionally Unprofessional
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.02644555107690394
  lightness: 0.03889205981977284
  saturation: 0.002770117251202464
  rhythmicContrast: 0.806695681065321
purpose: []
