layout_spectrum: 0.022303833393380046
typography_spectrum: 0.14294826984405518
color:
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
  brandStrength: 0.29251811909489334
  lightness: 0.012411735486239195
  saturation: 0.7497675453778356
  rhythmicContrast: 0.10154856159351766
content_rating:
  adult: false
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Silas Drew-Ch(Innes)
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ART x PHILOSOPHY = ARCHITECTURE
description: Professionally Unprofessional
purpose: []
