layout_spectrum: 0.9316292896401137
typography_spectrum: 0.3168774771038443
color:
  brandColors:
    - '#000000'
    - '#263248'
    - '#7E8AA2'
    - '#FFFFFF'
    - '#FF9800'
  brandStrength: 0.3144737728871405
  lightness: 0.9521363314706832
  saturation: 0.04772501764819026
  rhythmicContrast: 0.5495788725093007
content_rating:
  adult: false
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: Silas Drew-Ch(Innes)
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ART x PHILOSOPHY = ARCHITECTURE
description: Professionally Unprofessional
purpose: []
