typography_spectrum: 0.3426035800948739
content_rating:
  adult: false
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.3971672751940787
  lightness: 0.3227591279428452
  saturation: 0.7928702556528151
  rhythmicContrast: 0.0561836373526603
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8751923271920532
analytics:
  google: null
  facebook: null
  twitter: null
name: Silas Drew-Ch(Innes)
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: ART x PHILOSOPHY = ARCHITECTURE
description: Professionally Unprofessional
purpose: []
